### ISSUE TITLE
Hello! Is there any way to make Chinese and English characters have the same weight?

### ISSUE THREAD

**Issue by ChiaMeow** [treefarmstudio/odyssey-theme#29]
<img width="365" alt="image" src="https://github.com/littlesticks/odyssey-theme/assets/130277385/dee217d0-0b2b-4f2e-9a2b-e997e4efad5a">

<img width="584" alt="image" src="https://github.com/littlesticks/odyssey-theme/assets/130277385/9be81daf-47a3-4b7c-8ecc-ae4732cfecbf">

/* Special thanks to this tool for local fonts CSS generation:
  https://google-webfonts-helper.herokuapp.com/fonts/lato?subsets=latin
*/

/* roboto-serif-600 - latin */
@font-face {
  font-family: 'Noto Serif TC';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: local(''),
       url('/assets/fonts/noto-serif-tc-chinese-traditional-600-normal.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('/assets/fonts/noto-serif-tc-chinese-traditional-600-normal.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
/* roboto-serif-700 - latin */
@font-face {
  font-family: 'Noto Serif TC';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: local(''),
       url('/assets/fonts/noto-serif-tc-chinese-traditional-700-normal.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('/assets/fonts/noto-serif-tc-chinese-traditional-700-normal.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

/* lato-300 - latin */
@font-face {
  font-family: 'Noto Serif TC';
  font-style: normal;
  font-weight: 300;
  font-display: swap;
  src: local(''),
       url('/assets/fonts/noto-serif-tc-chinese-traditional-300-normal.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('/assets/fonts/noto-serif-tc-chinese-traditional-300-normal.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
/* lato-regular - latin */
@font-face {
  font-family: 'Noto Serif TC';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local(''),
       url('/assets/fonts/noto-serif-tc-chinese-traditional-400-normal.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('/assets/fonts/noto-serif-tc-chinese-traditional-400-normal.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
/* lato-700 - latin */
@font-face {
  font-family: 'Noto Serif TC';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: local(''),
       url('/assets/fonts/noto-serif-tc-chinese-traditional-700-normal.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('/assets/fonts/noto-serif-tc-chinese-traditional-700-normal.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
/* lato-700italic - latin */
@font-face {
  font-family: 'Noto Serif TC';
  font-style: italic;
  font-weight: 700;
  font-display: swap;
  src: local(''),
       url('/assets/fonts/noto-serif-tc-chinese-traditional-700-normal.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('/assets/fonts/noto-serif-tc-chinese-traditional-700-normal.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
:root {
  --font-size-sm: clamp(14.4px, 0.07vw + 14.13px, 15px);
  --font-size-base: clamp(18px, 0.23vw + 17.09px, 20px);
  --font-size-md: clamp(22.5px, 0.47vw + 20.61px, 26.66px);
  --font-size-lg: clamp(28.13px, 0.84vw + 24.76px, 35.54px);
  --font-size-xl: clamp(35.16px, 1.39vw + 29.6px, 47.37px);
  --font-size-xxl: clamp(43.95px, 2.18vw + 35.22px, 63.15px);
  --font-size-xxxl: clamp(54.93px, 3.32vw + 41.64px, 84.17px);
}

html,
body {
	line-height: 1.5;
	font-family: var(--theme-font-family-serif);
	font-size: var(--font-size-base);
	color: var(--theme-on-bg);
} 

h1,
h2,
h3 {
	font-family: var(--theme-font-family-serif);
	font-weight: 700;
}

h1 {
	font-size: var(--font-size-xxl);
}

h2 {
	font-size: var(--font-size-xl);
}

h3 {
	font-size: var(--font-size-lg);
}

h1,
h2 {
	line-height: 1.1;
	font-weight: 700;
}

h3 {
	font-weight: 500;
}

h6 {
	font-size: var(--font-size-sm);
}

h1,
h2,
h3,
h4,
h5,
h6,
p {
	margin: 0 0 1rem 0;
}

blockquote {
	font-style: italic;
	font-size: var(--font-size-base);
	font-weight: 500;
	margin-bottom: 1rem;
	padding-left: 1.5rem;
	border-left: 0.25rem solid var(--theme-on-bg);
}

**Comment by jaydanurwin** [comment]
Unfortunately, this would fall out of the scope of support I can offer for the theme as I don't have any experience with Chinese characters. Wishing you the best of luck though!
