### ISSUE TITLE
The score is not a perfect 100 in performance

### ISSUE THREAD

**Issue by dan-iliescu** [treefarmstudio/odyssey-theme#37]
<img width="491" alt="Screenshot 2023-09-09 at 05 01 29" src="https://github.com/littlesticks/odyssey-theme/assets/80542466/4b99df54-241f-4c5a-8e95-2290588aa112">

**Comment by jaydanurwin** [comment]
Unless you're planning on using Odyssey's preview images on your own site I don't think this would matter. However, I'll see what I can do with the recent 3.0 version to get it back to 100. 

Please keep in mind this metric is going to be dependent on **your** site and **your** content, the theme is simply giving you the tools and foundation needed to get a 100 with less effort.
